[general]
live_config_reload = true

[window]
decorations = "None"

[cursor.style]
blinking = "Never"

[font]
normal = { family = "DejaVu Sans Mono", style = "Book" }
bold = { family = "DejaVu Sans Mono", style = "Bold" }
size = 10

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black = "#000000"
red = "#cd0000"
green = "#00cd00"
yellow = "#cdcd00"
blue = "#0000cd"
magenta = "#cd00cd"
cyan = "#00cdcd"
white = "#e5e5e5"

[colors.bright]
black = "#7f7f7f"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#5c5cff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"
